#cloud-config
package_update: true
package_upgrade: true
packages:
  - mysql-server
runcmd:
  - systemctl enable mysql
  - systemctl start mysql
  - mysql -e "CREATE DATABASE ${database_name};"
  - mysql -e "CREATE USER '${database_user}'@'%' IDENTIFIED BY '${database_password}';"
  - mysql -e "GRANT ALL PRIVILEGES ON ${database_name}.* TO '${database_user}'@'%';"
  - mysql -e "FLUSH PRIVILEGES;"
